// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpteamixEmployeeManagementSystem.Data;

#nullable disable

namespace OpteamixEmployeeManagementSystem.Data.Migrations
{
    [DbContext(typeof(EmployeeDbContext))]
    partial class EmployeeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OpteamixEmployeeManagementSystem.Domain.Entities.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("JoiningDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");
                });


            modelBuilder.Entity("OpteamixEmployeeManagementSystem.Domain.Entities.TaskItem", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TaskId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("OpteamixEmployeeManagementSystem.Domain.Entities.Project", b =>
                        {
                            b.Property<int>("ProjectId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectId"));

                            b.Property<decimal>("Budget")
                                .HasColumnType("decimal(18,2)");

                            b.Property<string>("ClientName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b.Property<DateTime>("EndDate")
                                .HasColumnType("datetime2");

                            b.Property<int?>("ManagerId")
                                .HasColumnType("int");

                            b.Property<string>("ProjectName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b.Property<DateTime>("StartDate")
                                .HasColumnType("datetime2");

                            b.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b.HasKey("ProjectId");

                            b.HasIndex("ManagerId");

                            b.ToTable("Projects");
                        });

                    modelBuilder.Entity("OpteamixEmployeeManagementSystem.Domain.Entities.Project", b =>
                        {
                            b.HasOne("OpteamixEmployeeManagementSystem.Domain.Entities.Employee", "Manager")
                                .WithMany()
                                .HasForeignKey("ManagerId");

                            b.Navigation("Manager");

                        });

                }
    }
    }
